markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  toc_levels: 1..3
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    line_numbers: false

permalink: pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: default.liquid
gems:
  - jekyll-redirect-from
  - jekyll-optional-front-matter
exclude:
  - CNAME
  - Gulpfile.js
  - Gemfile
  - README.md
  - js
  - css
  - node_modules
baseurl: https://microsoft.github.io/prose
repository: Microsoft/prose

Title: Microsoft PROSE SDK
